import cv2
image = cv2.imread("rgbCircle.png")
B, G, R = cv2.split(image)
cv2.imshow("RGB Circles", image)
cv2.waitKey(0)
cv2.imshow("blue", B)
cv2.waitKey(0)
cv2.imshow("Green", G)
cv2.waitKey(0)
cv2.imshow("red", R)
cv2.waitKey(0)
cv2.destroyAllWindows()
